name: CI/CD

on:
  push:
    branches:
      - main  # Trigger for pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger for pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests (if you have them)
      - name: Run tests
        run: |
          # Make sure your test framework is set up (e.g., pytest)
          pytest tests/ --maxfail=1 --disable-warnings -q

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          curl -fsSL https://vercel.com/download -o vercel
          chmod +x vercel
          ./vercel --prod --token $VERCEL_TOKEN
